version: "2"

services:
  dns:
    container_name: radio_dns-dev
    network_mode: host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=53
      - RADIO_DOMAIN=radio.example.com
      - ALLOWED_DOMAIN=home.example.com,home2.example.com 
      - TIME_SERVER=ntp0.fau.de
    restart: always
