# Don't use this file for production, only for self building and running!
# See prebuild image and example file at:
#   https://hub.docker.com/r/kimbtechnologies/radio_dns

version: "2"

services:
  dns:
    container_name: radio_dns
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=53
      - RADIO_DOMAIN=radio.example.com
      - ALLOWED_DOMAIN=home.example.com,home2.example.com 
      - TIME_SERVER=ntp0.fau.de
    restart: always
